### ISSUE TITLE
PA Review: {User Authentication}

### ISSUE THREAD

**Issue by claytonchristian11** [claytonchristian11/Fullstack#1]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)

**Comment by jenvomo** [comment]
- [x] When logging, create an account, or sign in with demo user, `session` `id` is undefined.  
- [x] Cursor pointers are not showing up for login, demo login, sign up.
- [x] Error rendering does not match soundcloud
